apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edc-sha3-nginx-deployment
  labels:
    app: edc-sha3-nginx-app
    tier: edc-sha3-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edc-sha3-nginx-app
        tier: edc-sha3-nginx
    spec:
      volumes:
      - name: edc-sha3-nginx-pv-storage
        persistentVolumeClaim:
          claimName: edc-sha3-pv-claim
      containers:
      - name: edc-sha3-nginx
        image: "nginx:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: edc-sha3-nginx-pv-storage
          mountPath: "/tmp/nginx"
---
apiVersion: v1
kind: Service
metadata:
  name: edc-sha3-nginx-service
  labels:
    tier: edc-sha3-nginx
spec:
  type: ClusterIP
  selector:
    app: edc-sha3-nginx-app
    tier: edc-sha3-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: edc-sha3-nginx-port
