apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edc-sha3-regtest-deployment
  labels:
    app: edc-sha3-regtest-app
    tier: equibit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edc-sha3-regtest-app
        tier: equibit
    spec:
      volumes:
      - name: edc-sha3-regtest-pv-storage
        persistentVolumeClaim:
          claimName: edc-sha3-regtest-pv-claim
      containers:
      - name: edc-sha3-regtest
        image: "registry.ng.bluemix.net/equibit/edc-sha3-dev:latest"
        imagePullPolicy: Always
        volumeMounts:
        - name: edc-sha3-regtest-pv-storage
          mountPath: "/home/equibit/.equibit"
---
apiVersion: v1
kind: Service
metadata:
  name: edc-sha3-regtest-service
  labels:
    tier: equibit
spec:
  type: LoadBalancer
  selector:
    app: edc-sha3-regtest-app
    tier: equibit
  ports:
  - port: 18331
    targetPort: 18331
    protocol: TCP
    name: edc-sha3-regtest-port
  - port: 18333
    targetPort: 18333
    protocol: TCP
    name: edc-sha3-regtest-port-2
  - port: 18444
    targetPort: 18444
    protocol: TCP
    name: edc-sha3-regtest-port-3

