apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: equibit-miner-deployment
  labels:
    app: equibit-miner-app
    tier: equibit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: equibit-miner-app
        tier: equibit
    spec:
      containers:
      - name: equibit-miner
        image: "registry.ng.bluemix.net/equibit/eqb-miner-dev:latest"
        imagePullPolicy: Always
---
